/* ============================================================
   omrScanner.js — the computer-vision engine.

   Pipeline (matches the product architecture):
     image acquisition -> fiducial detection -> homography ->
     perspective rectification -> bubble-region sampling ->
     fill/darkness analysis -> multiple-mark detection ->
     confidence calculation -> answer extraction

   Because every sheet OMR Magic scans was generated by
   omrGenerator.js, the exact reference position of every bubble
   is already known. That lets this engine be genuinely reliable
   without a generic (and fragile) "guess the grid" algorithm —
   it only ever needs to find four corner markers, then read
   known coordinates. It never invents an answer: anything it
   isn't confident about comes back as 'unclear'.
   ============================================================ */

const OmrScanner = (() => {
  const RECT_W = 800, RECT_H = 1131; // rectified working resolution (keeps PAGE_W:PAGE_H ratio)

  const FILL_MIN = 82;      // darkness value above which a bubble reads as "marked"
  const BLANK_MAX = 50;     // darkness value below which a bubble reads as "empty"
  const CONFIDENCE_GAP = 28; // gap between top two candidates needed for high confidence

  // ---------- fiducial detection ----------
  // Looks for a solid dark square within a corner-sized search window.
  function findDarkSquare(grayImg, xr, yr) {
    const { gray, width, height } = grayImg;
    const x0 = Math.max(0, Math.floor(xr[0])), x1 = Math.min(width, Math.ceil(xr[1]));
    const y0 = Math.max(0, Math.floor(yr[0])), y1 = Math.min(height, Math.ceil(yr[1]));
    if (x1 <= x0 || y1 <= y0) return null;

    const step = Math.max(1, Math.floor((x1 - x0) / 90));
    let sum = 0, n = 0;
    for (let y = y0; y < y1; y += step) for (let x = x0; x < x1; x += step) { sum += gray[y * width + x]; n++; }
    const localMean = n ? sum / n : 200;
    const threshold = Math.min(140, localMean * 0.62);

    let sx = 0, sy = 0, cnt = 0;
    let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
    for (let y = y0; y < y1; y += step) {
      for (let x = x0; x < x1; x += step) {
        if (gray[y * width + x] < threshold) {
          sx += x; sy += y; cnt++;
          if (x < minX) minX = x; if (x > maxX) maxX = x;
          if (y < minY) minY = y; if (y > maxY) maxY = y;
        }
      }
    }
    if (cnt < 12) return null;
    const bw = maxX - minX, bh = maxY - minY;
    if (bw < 3 || bh < 3) return null;
    const squareness = Math.min(bw, bh) / Math.max(bw, bh);
    if (squareness < 0.35) return null; // too elongated to be a fiducial square

    const density = cnt / Math.max(1, ((bw / step) + 1) * ((bh / step) + 1));
    const confidence = Math.max(0, Math.min(1, squareness * 0.6 + density * 0.4));
    return { cx: sx / cnt, cy: sy / cnt, confidence };
  }

  function detectFiducials(grayImg) {
    const { width, height } = grayImg;
    const fx = 0.30, fy = 0.30; // search windows sized to ~30% of frame from each corner
    const regions = {
      tl: [[0, width * fx], [0, height * fy]],
      tr: [[width * (1 - fx), width], [0, height * fy]],
      bl: [[0, width * fx], [height * (1 - fy), height]],
      br: [[width * (1 - fx), width], [height * (1 - fy), height]],
    };
    const out = {};
    let allFound = true;
    for (const key of Object.keys(regions)) {
      const [xr, yr] = regions[key];
      const found = findDarkSquare(grayImg, xr, yr);
      out[key] = found;
      if (!found) allFound = false;
    }
    return { corners: out, allFound };
  }

  // ---------- fast heuristics for live camera guidance ----------
  function quickFrameAnalysis(imageData) {
    const grayImg = ImageProcessor.toGrayscale(imageData);
    const brightness = ImageProcessor.averageBrightness(grayImg);
    const glare = ImageProcessor.glareFraction(grayImg);
    const sharpness = ImageProcessor.sharpnessScore(grayImg);
    const { corners, allFound } = detectFiducials(grayImg);

    let coverage = null;
    if (allFound) {
      const xs = Object.values(corners).map(c => c.cx);
      const ys = Object.values(corners).map(c => c.cy);
      const w = Math.max(...xs) - Math.min(...xs);
      const h = Math.max(...ys) - Math.min(...ys);
      coverage = (w * h) / (grayImg.width * grayImg.height);
    }

    let message = null, status = 'searching';
    if (brightness < 70) { message = 'More light needed'; status = 'dark'; }
    else if (glare > 0.10) { message = 'Too much glare — tilt the sheet'; status = 'glare'; }
    else if (!allFound) { message = 'Align the OMR inside the frame'; status = 'searching'; }
    else if (coverage !== null && coverage < 0.28) { message = 'Move closer'; status = 'far'; }
    else if (coverage !== null && coverage > 0.92) { message = 'Move farther away'; status = 'close'; }
    else if (sharpness < 18) { message = 'Hold steady'; status = 'blurry'; }
    else { message = 'Sheet detected — hold steady'; status = 'ready'; }

    return { brightness, glare, sharpness, allFound, coverage, status, message, ready: status === 'ready' };
  }

  // ---------- full pipeline on a captured full-resolution frame ----------
  function processCapturedImage(sourceCanvas, template) {
    const ctx = sourceCanvas.getContext('2d');
    const imageData = ctx.getImageData(0, 0, sourceCanvas.width, sourceCanvas.height);
    const grayImg = ImageProcessor.toGrayscale(imageData);
    const { corners, allFound } = detectFiducials(grayImg);

    if (!allFound) {
      return { success: false, reason: 'sheet_not_detected', message: 'Couldn\u2019t find all four corner markers. Move the sheet fully inside the frame and try again.' };
    }

    const srcTemplatePts = [
      { x: template.fiducials.find(f => f.id === 'tl').cx, y: template.fiducials.find(f => f.id === 'tl').cy },
      { x: template.fiducials.find(f => f.id === 'tr').cx, y: template.fiducials.find(f => f.id === 'tr').cy },
      { x: template.fiducials.find(f => f.id === 'bl').cx, y: template.fiducials.find(f => f.id === 'bl').cy },
      { x: template.fiducials.find(f => f.id === 'br').cx, y: template.fiducials.find(f => f.id === 'br').cy },
    ];
    const dstPhotoPts = [corners.tl, corners.tr, corners.bl, corners.br].map(c => ({ x: c.cx, y: c.cy }));

    const H = ImageProcessor.computeHomography(srcTemplatePts, dstPhotoPts);
    if (!H) {
      return { success: false, reason: 'geometry_failed', message: 'The sheet\u2019s orientation is too distorted to read. Try a flatter angle.' };
    }

    // perspective sanity check
    const dx1 = dstPhotoPts[1].x - dstPhotoPts[0].x, dy1 = dstPhotoPts[1].y - dstPhotoPts[0].y;
    const dx2 = dstPhotoPts[2].x - dstPhotoPts[0].x, dy2 = dstPhotoPts[2].y - dstPhotoPts[0].y;
    const topLen = Math.hypot(dx1, dy1), leftLen = Math.hypot(dx2, dy2);
    const expectedRatio = (template.fiducials.find(f => f.id === 'tr').cx - template.fiducials.find(f => f.id === 'tl').cx) /
                          (template.fiducials.find(f => f.id === 'bl').cy - template.fiducials.find(f => f.id === 'tl').cy);
    const actualRatio = topLen / leftLen;
    const perspectiveDistortion = Math.abs(actualRatio - expectedRatio) / expectedRatio;
    if (perspectiveDistortion > 0.55) {
      return { success: false, reason: 'perspective_extreme', message: 'Perspective too extreme. Hold the camera more directly above the sheet.' };
    }

    const rectified = ImageProcessor.warpToTemplate(grayImg, H, RECT_W, RECT_H, template.pageWidth, template.pageHeight);
    const scaleX = RECT_W / template.pageWidth, scaleY = RECT_H / template.pageHeight;

    const brightness = ImageProcessor.averageBrightness(rectified);
    const glare = ImageProcessor.glareFraction(rectified);
    const sharpness = ImageProcessor.sharpnessScore(rectified);

    const warnings = [];
    if (sharpness < 14) warnings.push('Blur detected');
    if (brightness < 90) warnings.push('Low light');
    if (glare > 0.08) warnings.push('Glare detected');
    if (perspectiveDistortion > 0.3) warnings.push('Perspective slightly extreme');

    const cornerConfidence = (corners.tl.confidence + corners.tr.confidence + corners.bl.confidence + corners.br.confidence) / 4;
    let qualityScore = Math.round(Math.max(0, Math.min(100,
      cornerConfidence * 40 +
      Math.min(1, sharpness / 40) * 30 +
      Math.min(1, brightness / 180) * 20 +
      (1 - Math.min(1, glare * 6)) * 10
    )));

    // ---------- bubble reading ----------
    const bubbleR = template.bubbleRadius * scaleX;
    const detectedAnswers = template.questions.map(q => readQuestion(rectified, q, bubbleR, scaleX, scaleY));

    // ---------- roll number reading ----------
    let rollNumberResult = null;
    if (template.rollNumber) {
      rollNumberResult = readRollNumber(rectified, template.rollNumber, scaleX, scaleY);
    }

    const fingerprint = computeFingerprint(rectified, rollNumberResult);
    const previewDataUrl = grayToDataUrl(rectified);

    return {
      success: true,
      detectedAnswers,
      rollNumberResult,
      fingerprint,
      previewDataUrl,
      quality: { score: qualityScore, brightness: Math.round(brightness), sharpness: Math.round(sharpness), glare: Math.round(glare * 100), warnings, cornerConfidence: Math.round(cornerConfidence * 100) },
    };
  }

  function readQuestion(rectified, q, bubbleR, scaleX, scaleY) {
    const vals = q.options.map(o => ImageProcessor.circleDarkness(rectified, o.x * scaleX, o.y * scaleY, bubbleR));
    const maxV = Math.max(...vals);
    const sorted = [...vals].sort((a, b) => b - a);
    const secondV = sorted[1] !== undefined ? sorted[1] : 0;
    const markedIdx = vals.map((v, i) => ({ v, i })).filter(x => x.v >= FILL_MIN).map(x => x.i);

    if (maxV < BLANK_MAX) {
      return { option: null, status: 'blank', confidence: Math.max(0, Math.min(1, (BLANK_MAX + 8 - maxV) / 40)) };
    }
    if (markedIdx.length >= 2) {
      return { option: null, status: 'multiple', confidence: 0.3, candidates: markedIdx };
    }
    if (markedIdx.length === 1) {
      const gap = maxV - secondV;
      const confidence = Math.max(0.4, Math.min(1, gap / CONFIDENCE_GAP));
      if (gap < 10) return { option: null, status: 'unclear', confidence: 0.35 };
      return { option: markedIdx[0], status: 'answered', confidence };
    }
    // in the ambiguous zone between BLANK_MAX and FILL_MIN
    return { option: null, status: 'unclear', confidence: 0.3 };
  }

  function readRollNumber(rectified, rollTemplate, scaleX, scaleY) {
    const bubbleR = rollTemplate.bubbleR * scaleX;
    let digitsStr = '';
    let minConfidence = 1;
    let allClear = true;
    rollTemplate.columns.forEach(col => {
      const vals = col.bubbles.map(b => ImageProcessor.circleDarkness(rectified, b.x * scaleX, b.y * scaleY, bubbleR));
      const maxV = Math.max(...vals);
      const sorted = [...vals].sort((a, b) => b - a);
      const gap = maxV - (sorted[1] || 0);
      if (maxV < FILL_MIN || gap < 10) { allClear = false; digitsStr += '?'; minConfidence = Math.min(minConfidence, 0.3); return; }
      const idx = vals.indexOf(maxV);
      digitsStr += String(col.bubbles[idx].value);
      minConfidence = Math.min(minConfidence, Math.max(0.5, Math.min(1, gap / CONFIDENCE_GAP)));
    });
    return { rollNumber: allClear ? digitsStr : null, raw: digitsStr, confidence: minConfidence, clear: allClear };
  }

  // simple average-hash style fingerprint of the rectified sheet, combined with roll number
  function computeFingerprint(rectified, rollResult) {
    const gridSize = 12;
    const stepX = Math.floor(rectified.width / gridSize), stepY = Math.floor(rectified.height / gridSize);
    let hash = '';
    for (let gy = 0; gy < gridSize; gy++) {
      for (let gx = 0; gx < gridSize; gx++) {
        const v = ImageProcessor.bilinearGray(rectified, gx * stepX + stepX / 2, gy * stepY + stepY / 2);
        hash += v > 150 ? '0' : '1';
      }
    }
    const rollPart = (rollResult && rollResult.rollNumber) ? rollResult.rollNumber : '';
    return rollPart + ':' + hash;
  }

  function grayToDataUrl(grayImg) {
    const canvas = document.createElement('canvas');
    canvas.width = grayImg.width; canvas.height = grayImg.height;
    const ctx = canvas.getContext('2d');
    const imgData = ctx.createImageData(grayImg.width, grayImg.height);
    for (let i = 0, p = 0; p < grayImg.gray.length; p++, i += 4) {
      const v = Math.max(0, Math.min(255, grayImg.gray[p]));
      imgData.data[i] = v; imgData.data[i + 1] = v; imgData.data[i + 2] = v; imgData.data[i + 3] = 255;
    }
    ctx.putImageData(imgData, 0, 0);
    return canvas.toDataURL('image/jpeg', 0.72);
  }

  return { quickFrameAnalysis, processCapturedImage, detectFiducials };
})();
